### ISSUE TITLE
Memory leak on Firefox, Chrome and Edge using either Tampermonkey or Violentmonkey addons

### ISSUE THREAD

**Issue by Jurtaani** [najdek/f1tv_plus#30]
I'm using those browsers on Windows 10 on machine with 32gb ram and got around 11-15 laps until edge told me that it had ran out of memory and the tab crashed on me.
so i had to relaunch my four broadcast session 5 times on the last race and twice during sprint.
had this been on issue on Firefox which is my main browser, then i could have put it as some other thing leaking memory on there.
but both Chrome and Edge are basically stock except for Tampermonkey and this script, so i suspect that that drm solution of yours leaks memory until the tab crashes.

same doesn't happen on drm free archived stuff, so i'm sure that it is related to that solution of yours.

**Comment by najdek** [comment]
The script is now very simple. There isn't any drm workaround in it. New drm videos are treated exactly the same as old archived videos.
It just loads multiple instances of the full F1TV page into multiple windows/iframes.
This is memory-intensive so a browser might kill the tabs because of strict memory management.
If there is any memory leak, then it's probably on the F1TV side.

**Comment by Jurtaani** [comment]
well that is worrisome to hear´, because if the issue indeed lies on F1TV themself. maybe even Leclerc has retired from F1 due to his old age before they fix the issue.
but it is indeed related to their drm solution, as i can easily watch the whole race using this script if it has been moved to drm free archive.

**Comment by chrcoluk** [comment]
Was about to post this issue.

Luckily I have 32 gigs of ram, so got away with it.

6 popout windows.  Right at end of Max interview post race, Firefox started becoming unstable, first the streams all just died so black windows.  Then I noticed I couldnt open new tabs, they were instant crashing.  I opened task manager after I closed firefox and can see the culprit, lack of memory to allocate.  I thought tampermonkey might be to blame as I know in the past its not as performant as violentmonkey, of course had to switch as tampermonkey needed for the popups, but the OP says it handles on violentmonkey as well.

![f1tvmemleak](https://user-images.githubusercontent.com/8260578/169701817-ab96cfd4-2ba8-43de-94e1-ddfd6fe68817.png)

**Comment by chrcoluk** [comment]
Some notes from monaco quali.

Using the 6 window layout, f1 live, data, and 4 onboards.

Q1 and  Q2 all set to auto resolution.

System memory usage early on 7.1 gigs, 7.8 after 7 mins, 10.3 after 18 mins, 15.4 end of Q2.

Then switched all onboards to 360p to see what effect would have, I accidentally had to refresh all the streams, so memory usage went down a bit, so will post offset from start of Q3.

2.4gigs increase in memory usage during Q3. 

19.1 gigs system memory used when closed f1 windows, 5.5 gigs after windows closed.

I also checked memory usage by the rendering process, was at 13.4 gigs firefox.exe that was the child process for f1tv.

**Comment by najdek** [comment]
There's definitely something wrong with memory management on F1TV website.
Here are results of two tests I did today (Monaco quali and post-quali show).
![image](https://user-images.githubusercontent.com/4890607/170838121-ef31fe01-c979-46d1-a005-d116107cc778.png)
![image](https://user-images.githubusercontent.com/4890607/170838130-618b951e-d9e0-449a-b440-3df9c21d8bdb.png)
Tests done on "clean" website, without loading any userscripts. On a system with 32GB RAM.
In both tests, Chrome crashed the tab when RAM usage went over 6GB.

I'm closing this issue, as it's not related to the userscript.
I don't think we can work around this issue because of the lately introduced DRM.

**Comment by Jurtaani** [comment]
yeah it behaves the same on every browser and the leaks go away onle after Widevine DRM is removed.
however, i have since noticed that Firefox is happy to let F1TV to enter "all you can eat" ram buffee.
so i was able to use  F1TV+ script on otherwise clean Firefox portable profile, and FP2, FP3 and qualifying went rather smoothly.
yeah after each session Firefox portable went from 600mb to  8,5-9gb ram usage, but the web player performance stayed "fine" and those F1TV tabs never crashed on me.
so until F1TV fixes the issue on their site, it seems like Firefox 64bit is the only viable option for now.
